name: CI - Helm Image Puller

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          echo "Installing ShellCheck"
          sudo apt-get install -y shellcheck
          echo "Installing Docker"
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          echo "Installing Helm"
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Run ShellCheck (Linting)
        run: shellcheck pull_helm_images.sh

      - name: Test Script (Dry Run)
        run: ./pull_helm_images.sh -l -s jenkins/jenkins || echo "Script failed" && exit 1
