name: CI - Helm Image Puller

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 🛠 Install Dependencies
        run: |
          set -e
          chmod +x install_deps.sh
          ./install_deps.sh

      - name: Run ShellCheck (Linting)
        run: shellcheck pull_helm_images.sh

      - name: Add Jenkins Helm Repo
        run: |
          set -e
          helm repo add jenkins https://charts.jenkins.io
          helm repo update

      - name: Test Script (Dry Run)
        run: |
          set -e
          ./pull_helm_images.sh -l -s jenkins/jenkins
